# DDM with collapsing bounds in Stan {#ddmstan}

(TL;DR) I attempt to fit a collapsing boundary DDM using Stan.

## Introduction

Yep.

## Methods

Yeppers.

### Prep Work {.tabset}

#### Load Libraries {-}

```{r message=FALSE, messages=FALSE}

rm(list = ls())
seed <- 1337
set.seed(seed)

if("pacman" %in% rownames(installed.packages()) == FALSE) {install.packages("pacman")}
pacman::p_load("dplyr", "ggplot2", "rstan", "shinystan", "truncnorm")

```

#### Load Data {-}

Taken from Eum and Rangel (2022).

```{r}

load("D:/OneDrive - California Institute of Technology/PhD/Rangel Lab/2021-gaze-contingent-displays/03 joint/temp/cfr.R")
cfr <- cfr[cfr$parcode==201,]

```

## Run Stan

```{r}

# find and use cores
core.count <- as.numeric(parallel::detectCores())
core.use <- floor(core.count/2)
options(mc.cores = core.use)

# Compile the Stan model
stan.model <- stan_model("practice_stan_model.stan")

# stan data
stan.data <- list(
  N = N,
  Y = Y
)

# pass data to stan model
set.seed(seed)
stan.fit <- 
  sampling(
    stan.model, 
    stan.data,
    iter = 200,
    chains = core.use
  )

```

## Diagnose our fit

```{r}

launch_shinystan(stan.fit)

```

